services:
  backend:
    build: ./backend
    ports:
      - "8080:8080"
    volumes:
      - ./data:/data
    environment:
      - DATABASE_URL=/data/conduit.db
      - JWT_SECRET=your-secret-key-change-in-production
      - PORT=8080
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/health"]
      timeout: 5s
      retries: 5
      start_period: 30s
    restart: unless-stopped

volumes:
  data:
    driver: local