name: Deploy Frontend to GitHub Pages

on:
  push:
    branches: [ main ]
    paths: [ 'frontend/**' ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json

      - name: Install dependencies
        run: cd frontend && npm ci

      - name: Check required variables
        run: |
          if [ -z "${{ vars.BACKEND_URL }}" ]; then
            echo "❌ Error: BACKEND_URL variable is not set"
            echo "Please set BACKEND_URL in repository variables"
            exit 1
          fi
          echo "✅ Using BACKEND_URL: ${{ vars.BACKEND_URL }}"

      - name: Build
        run: cd frontend && npm run build
        env:
          VITE_API_URL: ${{ vars.BACKEND_URL }}

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./frontend/dist

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

  e2e-tests:
    name: Run E2E Tests After Frontend Deployment
    needs: deploy
    uses: ./.github/workflows/e2e-tests.yml
    with:
      backend_url: ${{ vars.BACKEND_URL }}
      frontend_url: ${{ vars.FRONTEND_URL }}
    secrets: inherit